---
- name: Install required system packages
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: Add Docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum:
    name: "{{ packages }}"
    state: "{{ docker_version }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes