---
- name: Deploy Dockerized Flask App on EC2
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Flask app repository
      git:
        repo: 'https://github.com/VishakhaArote/networking_project.git'
        dest: /home/ubuntu/networking_project
        version: main

    - name: Build Docker image
      command: docker build -t flask-app .
      args:
        chdir: /home/ubuntu/networking_project/DockerApp

    - name: Run Docker container
      command: docker run -d -p 80:80 flask-app
